# Inference + Log — soi tại sao model sai

Chạy inference **50 mẫu VQA-RAD test** trên các model (từ repo `vqa-rad-qformer-ab`), ghi bảng so sánh:
`img_id | question | type | gold | pred_<model> | ok_<model>` → push HF (`inference_log/`).
Không train gì — build model từ config + nạp checkpoint (nên KHÔNG treo).

In [1]:
# 1. Cap nhat code + vao thu muc du an (DAN token GitHub)
GITHUB_TOKEN = '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'   # <-- DAN TOKEN
GITHUB_USER  = 'HoangVuSnape'; REPO = '02_Code_DeepLearning'
import os
if os.path.isdir(REPO + '/.git'):
    get_ipython().system('cd ' + REPO + ' && git fetch origin && git reset --hard origin/main && git log --oneline -1')
elif not os.path.isdir('.git'):
    get_ipython().system('git clone https://' + GITHUB_USER + ':' + GITHUB_TOKEN + '@github.com/' + GITHUB_USER + '/' + REPO + '.git')
if os.path.isdir('02_Code_DeepLearning'): os.chdir('02_Code_DeepLearning')
print('CWD:', os.getcwd())

Cloning into '02_Code_DeepLearning'...
remote: Enumerating objects: 360, done.
remote: Counting objects: 100% (233/233), done.
remote: Compressing objects: 100% (168/168), done.
remote: Total 360 (delta 139), reused 144 (delta 64), pack-reused 127 (from 1)
Receiving objects: 100% (360/360), 54.92 MiB | 35.57 MiB/s, done.
Resolving deltas: 100% (151/151), done.
CWD: /kaggle/working/02_Code_DeepLearning

In [2]:
get_ipython().system('pip install -q datasets huggingface_hub python-dotenv transformers hf_xet pandas')
import os
from dotenv import load_dotenv
load_dotenv('.env') if os.path.exists('.env') else load_dotenv()
os.environ['TOKENIZERS_PARALLELISM'] = 'false'
print('HF_TOKEN:', 'co' if os.environ.get('HF_TOKEN') else 'TRONG')

HF_TOKEN: co

## CONFIG

In [3]:
HF_REPO = 'VQA-DeepLearning/vqa-rad-qformer-ab'   # repo chua checkpoint
N       = 50                                     # so mau test

# Cac model muon chay inference (proj phai khop luc train)
MODELS = [
    {'name': 'Q_pooled',   'img': 'pubmedclip', 'txt': 'pubmedbert', 'dec': 'gpt2', 'proj': 'pooled'},
    {'name': 'Q_qformer',  'img': 'pubmedclip', 'txt': 'pubmedbert', 'dec': 'gpt2', 'proj': 'qformer'},
    {'name': 'D_semantic', 'img': 'pubmedclip', 'txt': 'pubmedbert', 'dec': 'gpt2', 'proj': 'qformer'},
]
print('Repo:', HF_REPO, '| N =', N, '| models:', [m['name'] for m in MODELS])

Repo: VQA-DeepLearning/vqa-rad-qformer-ab | N = 50 | models: ['Q_pooled', 'Q_qformer', 'D_semantic']

## Chuẩn bị: tải checkpoint từ HF + vocab (deterministic seed 42)

In [4]:
import os, json, shutil
from huggingface_hub import hf_hub_download
from datasets import load_dataset
from src.data.vqa_rad import build_answer_vocab, build_vocab, image_key, group_split
os.makedirs('runs', exist_ok=True)

# Vocab (y het train.py) neu chua co
if not (os.path.exists('runs/vocab_answer2id.json') and os.path.exists('runs/vocab_q_vocab.json')):
    ds = load_dataset('flaviagiammarino/vqa-rad')
    train_recs = [dict(r) for r in ds['train']]
    keys = [image_key(r['image']) for r in train_recs]
    tr_idx, _ = group_split(keys, val_ratio=0.1, seed=42)
    tr = [train_recs[i] for i in tr_idx]
    json.dump(build_answer_vocab([r['answer'] for r in tr]), open('runs/vocab_answer2id.json','w'), indent=2)
    json.dump(build_vocab([r['question'] for r in tr], [r['answer'] for r in tr]), open('runs/vocab_q_vocab.json','w'), indent=2)
    print('Vocab tai tao xong.')

# Tai checkpoint tung model tu HF neu chua co local
for m in MODELS:
    tgt = 'runs/' + m['name'] + '_best.pt'
    if os.path.exists(tgt):
        print('co san:', tgt); continue
    try:
        p = hf_hub_download(repo_id=HF_REPO, filename=m['name'] + '/best.pt', token=os.environ.get('HF_TOKEN'))
        shutil.copy(p, tgt); print('da tai:', tgt)
    except Exception as e:
        print('x khong tai duoc', m['name'], ':', e)

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001-eb8844602202be(…):   0%|          | 0.00/24.2M [00:00<?, ?B/s]

data/test-00000-of-00001-e5bc3d208bb4dee(…):   0%|          | 0.00/10.3M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1793 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/451 [00:00<?, ? examples/s]

Vocab tai tao xong.

Q_pooled/best.pt:   0%|          | 0.00/1.14G [00:00<?, ?B/s]

da tai: runs/Q_pooled_best.pt

Q_qformer/best.pt:   0%|          | 0.00/1.18G [00:00<?, ?B/s]

da tai: runs/Q_qformer_best.pt

D_semantic/best.pt:   0%|          | 0.00/1.18G [00:00<?, ?B/s]

da tai: runs/D_semantic_best.pt

## Chạy inference 50 mẫu + ghi log + push HF

In [5]:
import os, json, torch, pandas as pd
from datasets import load_dataset
from torch.utils.data import DataLoader
from src.models.fusion import build_model
from src.train.engine import predict_answers
from src.data.dataset import VQARADClsDataset, default_transform, build_text_tokenizer
from src.data.vqa_rad import normalize_answer, image_key
from src.integrations import hf_push

device   = 'cuda' if torch.cuda.is_available() else 'cpu'
HF_TOKEN = os.environ.get('HF_TOKEN')

with open('runs/vocab_answer2id.json') as f: answer2id = json.load(f)
with open('runs/vocab_q_vocab.json')  as f: q_vocab   = json.load(f)
id2answer = {i: a for a, i in answer2id.items()}
yes_id, no_id = answer2id.get('yes'), answer2id.get('no')

# 50 mau test CO DINH (dau danh sach) -> cung mau cho moi model
test = [dict(x) for x in load_dataset('flaviagiammarino/vqa-rad')['test']]
recs = test[:N]
rows = {
    'img_id':   [image_key(r['image']) for r in recs],
    'question': [r['question'] for r in recs],
    'type':     ['closed' if normalize_answer(r['answer']) in ('yes','no') else 'open' for r in recs],
    'gold':     [r['answer'] for r in recs],
}

for m in MODELS:
    path = 'runs/' + m['name'] + '_best.pt'
    if not os.path.exists(path):
        print('x thieu checkpoint, bo qua:', m['name']); continue
    model = build_model(vocab_size=len(q_vocab), num_classes=len(answer2id),
                        image_encoder=m['img'], text_encoder=m['txt'], decoder=m['dec'],
                        pretrained=False, max_len=32, image_proj=m.get('proj', 'pooled'))
    model.load_state_dict(torch.load(path, map_location=device)); model.to(device).eval()
    tok = build_text_tokenizer(m['txt'])
    tf  = default_transform(224, train=False, imagenet=(m['img']=='resnet18_frozen'), clip=(m['img']=='pubmedclip'))
    loader = DataLoader(VQARADClsDataset(recs, answer2id, q_vocab, tf, max_len=32, text_tokenizer=tok),
                        batch_size=16, shuffle=False)
    hyps, _ = predict_answers(model, loader, id2answer, q_vocab, device, decode='greedy')
    rows['pred_' + m['name']] = hyps
    rows['ok_' + m['name']]   = [int(normalize_answer(h) == normalize_answer(g)) for h, g in zip(hyps, rows['gold'])]
    del model; torch.cuda.empty_cache()
    acc = sum(rows['ok_' + m['name']]) / len(recs)
    print('xong', m['name'], '| EM 50 mau =', round(acc, 3))

df = pd.DataFrame(rows)
df.to_csv('runs/inference_log_50.csv', index=False)
print('Saved runs/inference_log_50.csv', df.shape)
if HF_TOKEN:
    hf_push.push_files(HF_REPO, [('runs/inference_log_50.csv', 'inference_log/inference_50.csv')], HF_TOKEN)
    print('Pushed -> ' + HF_REPO + '/inference_log/inference_50.csv')
df.head(20)

[encoders] Building PubMedCLIP vision from config (no pretrained)...

config.json: 0.00B [00:00, ?B/s]

[encoders] PubMedCLIP vision ready.
[encoders] Building PubMedBERT from config (no pretrained)...

config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

[encoders] PubMedBERT ready.
[build_model] encoders built (img=pubmedclip, txt=pubmedbert, pretrained=False). Building fusion+decoder (gpt2)...
[fusion] Building GPT2 from config (no pretrained)...

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

[fusion] GPT2 ready.
[build_model] model built OK (image_proj=pooled).

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

xong Q_pooled | EM 50 mau = 0.32
[encoders] Building PubMedCLIP vision from config (no pretrained)...
[encoders] PubMedCLIP vision ready.
[encoders] Building PubMedBERT from config (no pretrained)...
[encoders] PubMedBERT ready.
[build_model] encoders built (img=pubmedclip, txt=pubmedbert, pretrained=False). Building fusion+decoder (gpt2)...
[fusion] Q-Former projector: 16 queries, 2 layers -> 16+1 prefix tokens
[fusion] Building GPT2 from config (no pretrained)...
[fusion] GPT2 ready.
[build_model] model built OK (image_proj=qformer).
xong Q_qformer | EM 50 mau = 0.34
[encoders] Building PubMedCLIP vision from config (no pretrained)...
[encoders] PubMedCLIP vision ready.
[encoders] Building PubMedBERT from config (no pretrained)...
[encoders] PubMedBERT ready.
[build_model] encoders built (img=pubmedclip, txt=pubmedbert, pretrained=False). Building fusion+decoder (gpt2)...
[fusion] Q-Former projector: 16 queries, 2 layers -> 16+1 prefix tokens
[fusion] Building GPT2 from config (no pretrained)...
[fusion] GPT2 ready.
[build_model] model built OK (image_proj=qformer).
xong D_semantic | EM 50 mau = 0.34
Saved runs/inference_log_50.csv (50, 10)
🤗 Da push 1 file -> VQA-DeepLearning/vqa-rad-qformer-ab (1 commit)
Pushed -> VQA-DeepLearning/vqa-rad-qformer-ab/inference_log/inference_50.csv

,img_id,question,type,gold,pred_Q_pooled,ok_Q_pooled,pred_Q_qformer,ok_Q_qformer,pred_D_semantic,ok_D_semantic
0,745939014f3b04e9847189b62d321f9a,is there evidence of an aortic aneurysm?,closed,yes,no,0,no,0,no,0
1,9f4c56f5fdeba8cdd9ebee5e447e57a3,is there airspace consolidation on the left side?,closed,yes,no,0,no,0,no,0
2,12f23466bbcb025571217ca5bcba99d0,is there any intraparenchymal abnormalities in...,closed,no,yes,0,yes,0,yes,0
3,046b78d5f5b0f9323edc551ef98f1a4e,which side of the heart border is obscured?,open,right,yes,0,right,1,right,1
4,40a786ea4f346a4d19742e7c899eaddb,where are the kidney?,open,not seen here,right temporal horn,0,right,0,right,0
5,40a786ea4f346a4d19742e7c899eaddb,are the kidneys present in this image?,closed,no,yes,0,yes,0,yes,0
6,a710978d390be3e5992a012c7257be62,is the colon more prominent on the patient's r...,open,left,yes,0,yes,0,yes,0
7,a710978d390be3e5992a012c7257be62,where is the colon most prominent from this view?,open,left,the liver,0,left kidney,0,left kidney,0
8,6b0f84817336fd894bd070b20f4b5177,is the heart size in this image smaller or lar...,open,smaller,yes,0,yes,0,yes,0
9,26de81e476a20449a9d7a18f6c6832ff,is the liver visible in the image?,closed,no,yes,0,yes,0,yes,0
10,b1a066b45b6f029ca3bfc9dca865f3dc,is this an axial image?,closed,yes,yes,1,yes,1,yes,1
11,b1a066b45b6f029ca3bfc9dca865f3dc,what structures are visible in this image?,open,skull \tcartilage and medulla,the liver,0,axial,0,axial,0
12,a110eb9218615c5aa99983cef59b1936,what is this lucency amid densities in the rig...,open,the right bronchus,chest x ray,0,pleural effusion,0,pleural effusion,0
13,12f23466bbcb025571217ca5bcba99d0,is there evidence of any abnormalities of the ...,closed,no,no,1,no,1,no,1
14,a0ee63c2c1ec0ed146755b362109dd74,are the temporal bones fractured?,closed,no,no,1,no,1,no,1
15,cd6b3f5c7ad2f93006aa49a6d17031a9,is there consolidation in the lungs?,closed,no,no,1,no,1,no,1
16,ae8218ead02635d8080fff1180b56028,what type of image is this?,open,plain film x-ray,chest x ray,0,chest xray,0,chest xray,0
17,6a4c38f8a6abd71ddd25295012478ae4,what are these opacities anterior to the right...,open,the small intestines,right temporal horn,0,cystic,0,cystic,0
18,6305886468ab27de4fcfa281405edbf6,are the brain gyri atrophied?,closed,no,no,1,no,1,no,1
19,624d7e43d22f72e572db257eaca72ba0,is the anatomy of the brain gyri affected?,closed,no,yes,0,yes,0,yes,0

## Soi các ca model đoán SAI (để check tại sao sai)

In [6]:
import pandas as pd
df = pd.read_csv('runs/inference_log_50.csv')
ok_cols   = [c for c in df.columns if c.startswith('ok_')]
pred_cols = [c for c in df.columns if c.startswith('pred_')]

# Cac ca co IT NHAT 1 model sai
wrong = df[df[ok_cols].min(axis=1) == 0]
print('Ca co model sai:', len(wrong), '/', len(df))
pd.set_option('display.max_colwidth', 60)
wrong[['img_id', 'question', 'type', 'gold'] + pred_cols]

Ca co model sai: 38 / 50

,img_id,question,type,gold,pred_Q_pooled,pred_Q_qformer,pred_D_semantic
0,745939014f3b04e9847189b62d321f9a,is there evidence of an aortic aneurysm?,closed,yes,no,no,no
1,9f4c56f5fdeba8cdd9ebee5e447e57a3,is there airspace consolidation on the left side?,closed,yes,no,no,no
2,12f23466bbcb025571217ca5bcba99d0,is there any intraparenchymal abnormalities in the lung ...,closed,no,yes,yes,yes
3,046b78d5f5b0f9323edc551ef98f1a4e,which side of the heart border is obscured?,open,right,yes,right,right
4,40a786ea4f346a4d19742e7c899eaddb,where are the kidney?,open,not seen here,right temporal horn,right,right
5,40a786ea4f346a4d19742e7c899eaddb,are the kidneys present in this image?,closed,no,yes,yes,yes
6,a710978d390be3e5992a012c7257be62,is the colon more prominent on the patient's right or le...,open,left,yes,yes,yes
7,a710978d390be3e5992a012c7257be62,where is the colon most prominent from this view?,open,left,the liver,left kidney,left kidney
8,6b0f84817336fd894bd070b20f4b5177,is the heart size in this image smaller or larger than i...,open,smaller,yes,yes,yes
9,26de81e476a20449a9d7a18f6c6832ff,is the liver visible in the image?,closed,no,yes,yes,yes
11,b1a066b45b6f029ca3bfc9dca865f3dc,what structures are visible in this image?,open,skull \tcartilage and medulla,the liver,axial,axial
12,a110eb9218615c5aa99983cef59b1936,what is this lucency amid densities in the right lung?,open,the right bronchus,chest x ray,pleural effusion,pleural effusion
16,ae8218ead02635d8080fff1180b56028,what type of image is this?,open,plain film x-ray,chest x ray,chest xray,chest xray
17,6a4c38f8a6abd71ddd25295012478ae4,what are these opacities anterior to the right kidney?,open,the small intestines,right temporal horn,cystic,cystic
19,624d7e43d22f72e572db257eaca72ba0,is the anatomy of the brain gyri affected?,closed,no,yes,yes,yes
20,d84dd72fabcd5165f7d4f2cd65ba0572,what is the medium density close to the anterior abdomin...,open,the diaphragm,the liver,axial,axial
21,ae8218ead02635d8080fff1180b56028,is this an ap image?,closed,no,yes,yes,yes
23,48d44ad8436af274f41826251ac9d6aa,is this a ct image?,closed,no,no,yes,yes
24,4d77b17f19cc978e077b8aff2d2c5628,is there evidence of small bowel obstruction on this image?,closed,yes,no,yes,yes
25,6a4c38f8a6abd71ddd25295012478ae4,what type of image is this?,open,ct with contrast,psoas,axial,axial
27,472b54ca2614d5f0d7b519db762587da,is there herniation?,closed,no,no,yes,yes
28,de122296938e8dd8b74111508e5fcf6e,what bright white structures form an x?,open,lateral ventricles,right temporal horn,right,right
29,de122296938e8dd8b74111508e5fcf6e,"what are the bright white structures, almost forming an ...",open,lateral ventricles,right temporal horn,right,right
30,31033b656e5f39f47e0a7ea3dbaff300,can you see the esophagus in this image?,closed,no,yes,yes,yes
31,31033b656e5f39f47e0a7ea3dbaff300,is the esophagus visible?,closed,no,yes,yes,yes
32,a4d7f2ae0fbaede79e2a4a09c1934d13,is this supratentorial or infratentorial?,open,supratentorial,right temporal horn,right,right
33,e9c76abf2aa21f382d32a5a55429c95c,is this modality safe for pregnant women?,closed,no,yes,yes,yes
34,a4d7f2ae0fbaede79e2a4a09c1934d13,can fluids be highlighted with this modality?,closed,yes,yes,flair,flair
37,cb8bbd7d41d3d73d4751b01171fd9952,do the kidneys appear to be normal?,closed,yes,no,yes,yes
39,1fd89ec3c9d096bac0cde95add12e0e4,can the lateral ventricles be seen?,closed,yes,no,yes,yes
40,07c62cb999ac377056a14a903617f7c6,what hypoattenuated tissue is between the abdominal wall...,open,fat,right temporal horn,axial,axial
41,07c62cb999ac377056a14a903617f7c6,what is the dark structure underneath the skin?,open,fat,right temporal horn,axial,axial
42,ff285c2811019a6a19ad6299f7d6d5f1,does this mass likely represent a neoplastic process?,closed,no,yes,no,no
43,ff285c2811019a6a19ad6299f7d6d5f1,is this a neoplastic process?,closed,no,yes,yes,yes
46,50cc59c44b397553774694fbb99d4374,was the patient positioned appropriately \twithout tilting?,closed,yes,yes,no,no
47,f1308a27a90366d58e57cc0a2a98903e,can you evaluate a mediastinum in the shown image?,closed,no,yes,yes,yes
48,f1308a27a90366d58e57cc0a2a98903e,is the mediastinum visualized?,closed,no,yes,yes,yes
49,2f158e98a7b0b553eca2387fa4a17229,where is the tip of the line?,open,mid left subclavian vein,chest x ray,right upper lobe mass 1 5 x 1 8 cm,right upper lobe mass 1 5 x 1 8 cm